language: java
jdk:
        - openjdk8
addons:
        sonarcloud:
                organization: torkin1
                token:
                        secure: 4e99d32eb892fa6c7b94fc86ca75b1ab90b8bffe
notifications:
  	slack: mjstudygroup:aroIFvc9nvH41hQM5lQ1gZon

script: 
        - ant build
        - sonar-scanner
